//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace DancingGoat.Models
{
	/// <summary>
	/// Represents a content item of type <see cref="IndustryExpert"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class IndustryExpert : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "DancingGoat.IndustryExpert";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// IndustryExpertName.
		/// </summary>
		public string IndustryExpertName { get; set; }


		/// <summary>
		/// IndustryExpertTitle.
		/// </summary>
		public string IndustryExpertTitle { get; set; }


		/// <summary>
		/// IndustryExpertPhoto.
		/// </summary>
		public IEnumerable<Image> IndustryExpertPhoto { get; set; }


		/// <summary>
		/// IndustryExpertBio.
		/// </summary>
		public string IndustryExpertBio { get; set; }


		/// <summary>
		/// IndustryExpertWebsiteUrl.
		/// </summary>
		public string IndustryExpertWebsiteUrl { get; set; }
	}
}