//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace DancingGoat.Models
{
	/// <summary>
	/// Represents a content item of type <see cref="Endorsement"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Endorsement : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "DancingGoat.Endorsement";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// EndorsementExpert.
		/// </summary>
		public IEnumerable<IndustryExpert> EndorsementExpert { get; set; }


		/// <summary>
		/// EndorsementProduct.
		/// </summary>
		public IEnumerable<IContentItemFieldsSource> EndorsementProduct { get; set; }


		/// <summary>
		/// EndorsementQuote.
		/// </summary>
		public string EndorsementQuote { get; set; }


		/// <summary>
		/// EndorsementRating.
		/// </summary>
		public int EndorsementRating { get; set; }


		/// <summary>
		/// EndorsementDate.
		/// </summary>
		public DateTime EndorsementDate { get; set; }
	}
}